service-type = "DN"
data-dir = "./mo-data"

[log]
level = "info"
format = "json"
max-size = 512

[hakeeper-client]
service-addresses = [
  "127.0.0.1:32000",
]


[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "S3"
backend = "MEM"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[dn]
uuid = "dn1"

[dn.Txn.Storage]
backend = "TAE"
log-backend = "logservice"

[dn.Ckp]
scanner-interval = "100000s"
flush-interval = "100000s"
min-count = 2000000
scan-interval = "100000s"
incremental-interval = "100000s"
global-interval = "100000s"
