#!/bin/bash

echo "🔄 Data Comparison Demo"
echo "======================="
echo ""
echo "This demo shows how to compare data between two time points"
echo "and analyze changes in labels, metadata, and annotations."
echo ""
echo "Features:"
echo "- Compare data at two different timestamps"
echo "- Show detailed differences in labels, annotators, confidence"
echo "- Display summary statistics"
echo "- Analyze label distribution changes"
echo ""
echo "Example usage:"
echo "1. Run: ./ai_dataset_demo -host 10.222.1.52 -interactive"
echo "2. Choose option 6 (Compare Two Time Points)"
echo "3. Enter two timestamps like:"
echo "   Time 1: 2025-09-09 13:06:20"
echo "   Time 2: 2025-09-09 13:06:24"
echo ""
echo "The system will show:"
echo ""
echo "📋 Detailed Mode (Default):"
echo "- Record-by-record differences with full details"
echo "- Specific changes: Label 'A' → 'B', Annotator 'X' → 'Y'"
echo "- Complete metadata information (annotator, confidence, reason)"
echo "- Timestamps for each change"
echo ""
echo "📊 Summary Mode:"
echo "- Statistical overview of changes"
echo "- Added/removed/modified record counts"
echo "- Label distribution changes"
echo "- Quick overview without detailed records"
echo ""
echo "This demonstrates MatrixOne's Git for Data capabilities"
echo "for tracking data evolution and annotation changes!"
