#!/bin/bash

echo "📸 Snapshot Management Demo"
echo "============================"
echo ""
echo "This demo shows how to use MatrixOne's snapshot functionality"
echo "for data versioning and comparison."
echo ""
echo "Features:"
echo "- Create snapshots with custom names"
echo "- View all available snapshots"
echo "- Delete snapshots"
echo "- Compare two snapshots with detailed diff"
echo ""
echo "Example usage:"
echo "1. Run: ./ai_dataset_demo -host 10.222.1.52 -interactive"
echo "2. Choose option 7 (Snapshot Management)"
echo "3. Create snapshots at different stages:"
echo "   - Initial data: 'initial'"
echo "   - After AI annotation: 'after_ai'"
echo "   - After human review: 'after_human'"
echo ""
echo "Snapshot naming convention:"
echo "- Format: ai_dataset_YYYYMMDD_HHMMSS_suffix"
echo "- Example: ai_dataset_20250909_143022_initial"
echo ""
echo "SQL Commands:"
echo "- Create: CREATE SNAPSHOT snapshot_name FOR TABLE test ai_dataset"
echo "- List: SHOW SNAPSHOTS"
echo "- Delete: DROP SNAPSHOT snapshot_name"
echo "- Query: SELECT * FROM ai_dataset {Snapshot = \"snapshot_name\"}"
echo ""
echo "Comparison features:"
echo "- Detailed mode: Record-by-record differences"
echo "- Summary mode: Statistical overview"
echo "- Shows label changes, metadata updates, timestamps"
echo ""
echo "This demonstrates MatrixOne's Git for Data capabilities"
echo "with snapshot-based versioning!"
